name: Remove .html from URLs

on:
  push:
    branches:
      - main  # Измените на вашу основную ветку, если она отличается

jobs:
  rename_html_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Rename HTML files and update links
        run: |
          # Удаляем .html из всех файлов в репозитории
          find . -name '*.html' | while read file; do
            mv "$file" "${file%.html}"
          done

          # Заменяем ссылки в других HTML файлах
          find . -name '*.html' | while read file; do
            sed -i 's/\.html//g' "$file"
          done

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Removed .html extension from URLs" || echo "No changes to commit"

      - name: Push changes
        run: git push origin main  # Измените на вашу основную ветку, если она отличается
